### ISSUE TITLE
Clarification on Popularity_1_Year Metric and Found Boolean in Artifact Node

### ISSUE THREAD

**Issue by rabbi123080** [Goblin-Ecosystem/goblinTutorial#1]
I have a couple of questions regarding specific features within the dataset.

1. Popularity_1_Year: Could you please clarify what this metric represents? For example, if an artifact version was released on January 1, 2023, and the popularity_1_year value is 59, what does this mean?
2. Artifact Node - Found Boolean: I would also appreciate your insight into the 'found' boolean attribute in the artifact node. What does it indicate about the artifacts within the dataset? I have noticed that some artifacts have 'found' equal to 'false'.

**Comment by pascalpoizat** [comment]
Hello @rabbi123080 

1. **Popularity_1_Year**

I think the explanation here in section 6.1 is more clear:

[https://hal.science/hal-04684254v1/](https://hal.science/hal-04684254v1/file/ASE24_preprint.pdf)

It is the number of dépendants of the version of the library over a one year window (back from the date of the dependency graph).
See also getReleasePopularity1Year here 

https://github.com/Goblin-Ecosystem/goblinWeaver/blob/65bff610455adc70ce5322a181be412465c5c9bf/src/main/java/com/cifre/sap/su/goblinWeaver/graphDatabase/neo4j/Neo4jQueryDictionary.java

Say your database is from Sept 1st, 2024 (I do not remember the date of the last one we put on Zenodo, further with the miner one can update it quite easily)
And you are interested in the popularity of g:a:v (the version v of a library g:a)
Then you look in the graph (using a Cypher query) for all dependencies g2:a2:v2 —— v —-> g:a (a dependency relation is between a library version and a library, with required version or range associated to the edge)
Such that the release date for g2:a2:v2 is between Sept 1st 2023 and Sept 1st 2024
And then count all such dependency edges.
Here in your example, 59.
It is the date of the database and the release date of the dependents that are important, not the one of the release whose popularity is computed.


We will update the tutorial to make this more clear.

2. **Artifact Node - Found Boolean**

The found Boolean should be used to know whether the node has been found in the ecosystem or not. Sometimes you have A depending on B but you do not find B in the Maven central so you set found to false.

**Action :** (@pascalpoizat or @DaJaime) update the tutorial and all other necessary documentation accordingly.

**Comment by rabbi123080** [comment]
Thank you for your assistance regarding my questions about the dataset. I appreciate your insights.
